
dnsbl_zones = [
    'cbl.abuseat.org',
    'dnsbl.sorbs.net',
    'dul.dnsbl.sorbs.net',
    'smtp.dnsbl.sorbs.net',
    'spam.dnsbl.sorbs.net',
    'zombie.dnsbl.sorbs.net',
    'sbl.spamhaus.org',
    'zen.spamhaus.org',
    'psbl.surriel.com',
    'rbl.spamlab.com',
    'noptr.spamrats.com', 
    'cbl.anti-spam.org.cn', 
    'dnsbl.inps.de', 
    'httpbl.abuse.ch', 
    'short.rbl.jp', 
    'spamrbl.imp.ch', 
    'virbl.bit.nl', 
    'dsn.rfc-ignorant.org', 
    'opm.tornevall.org', 
    'multi.surbl.org', 
    'tor.dan.me.uk', 
    'relays.mail-abuse.org', 
    'rbl-plus.mail-abuse.org', 
    'access.redhawk.org', 
    'rbl.interserver.net', 
    'bogons.cymru.com', 
    'truncate.gbudb.net', 
    'bl.spamcop.net', 
    'b.barracudacentral.org', 
    'http.dnsbl.sorbs.net', 
    'misc.dnsbl.sorbs.net', 
    'socks.dnsbl.sorbs.net', 
    'web.dnsbl.sorbs.net', 
    'pbl.spamhaus.org', 
    'xbl.spamhaus.org', 
    'ubl.unsubscore.com', 
    'dyna.spamrats.com', 
    'spam.spamrats.com', 
    'cdl.anti-spam.org.cn', 
    'drone.abuse.ch', 
    'korea.services.net', 
    'virus.rbl.jp', 
    'wormrbl.imp.ch', 
    'rbl.suresupport.com', 
    'spamguard.leadmon.net', 
    'netblock.pedantic.org', 
    'ix.dnsbl.manitu.net', 
    'rbl.efnetrbl.org', 
    'blackholes.mail-abuse.org', 
    'dnsbl.dronebl.org', 
    'db.wpbl.info', 
    'query.senderbase.org', 
    'csi.cloudmark.com',

    # 'bl.spamcannibal.org', 
    # 'combined.njabl.org', 
    # 'dnsbl.njabl.org',

]
